services:
  symfony_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8011:9000"
    volumes:
      - /data/workspace/maeh:/var/www
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  symfony_web:
    image: nginx:1.22-alpine
    container_name: symfony_web
    ports:
      - "8082:80"
    volumes:
      - /data/workspace/maeh:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/app.conf:ro
    depends_on:
      - symfony_app

  symfony_db:
    image: postgres:16-alpine
    container_name: symfony_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgdata:/var/lib/pgadmin
    depends_on:
      - symfony_db


volumes:
  pgdata: