# version: '3.8'

# services:
#   maeh:
#     build: .
#     container_name: maeh-app
#     restart: unless-stopped
#     ports:
#       - "3003:9000"  # Port interne exposé si besoin
#     volumes:
#       - .:/var/www
#     networks:
#       - proxy-tier

# networks:
#   proxy-tier:
#     external: true